# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b021d84cc27d572ac28c74b192e9d3d1"
name = "Product App Badge"
handle = "product-app-badge"
application_url = "https://product-app-badge.vercel.app"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://product-app-badge.vercel.app/auth/callback",
  "https://product-app-badge.vercel.app/auth/shopify/callback",
  "https://product-app-badge.vercel.app/api/auth/callback"
]

[pos]
embedded = false
